kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jmeter-scaler-binding
  namespace: perf
subjects:
- kind: ServiceAccount
  name: jmeter-service-account
  namespace: perf
roleRef:
  kind: Role
  name: jmeter-scaler-role
  apiGroup: rbac.authorization.k8s.io
